// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syszirlkxzsgxhcpegmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5c3ppcmxreHpzZ3hoY3BlZ21nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMzkzNjIsImV4cCI6MjA3MjkxNTM2Mn0.uGD3gWJA8FxrG85m5qRK6N2S7hOUV_NP_VruMC1-cUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});